=== ePages-de/epages-docs/_raml/v-7.5.0/apps/products/schema/get_product_productid_variations.schema.json
{
  "$schema": "http://json-schema.org/draft-03/schema",
  "title": "Get Product ProductId Variations Schema",
  "type": "object",
  "properties": {
    "variationAttributes": {
      "type": "array of [variationAttribute](page:apps-data-types#variationattribute)",
      "description": "The existing variations of the product, e.g. colour."
    },
    "items": {
      "type": "array of [variation](page:apps-data-types#variation)",
      "description": "The available variations of the product that are set visible in the administration area of the shop."
    },
    "results": {
      "type": "integer",
      "description": "The number of variations in total."
    },
    "resultsPerPage": {
      "type": "integer",
      "description": "The number of variations returned per page."
    },
    "page": {
      "type": "integer",
      "description": "The page number on which the variation appears."
    },
    "links": {
      "type": "array of [link](page:apps-data-types#link)",
      "description": "The links to the product variations."
    }
  }
}

=== ePages-de/epages-docs/_raml/v-6.17.51/apps/products/examples/get_product_productid_variations_response.json
{
  "variationAttributes": [
    {
      "name": "Colour",
      "displayName": "Colour",
      "values": [
        {
          "value": "Black",
          "displayValue": "Black"
        },
        {
          "value": "Silver",
          "displayValue": "Silver"
        },
        {
          "value": "Red",
          "displayValue": "Red"
        },
        {
          "value": "White",
          "displayValue": "White"
        },
        {
          "value": "Orange",
          "displayValue": "Orange"
        },
        {
          "value": "Blue",
          "displayValue": "Blue"
        },
        {
          "value": "Green",
          "displayValue": "Green"
        },
        {
          "value": "Yellow",
          "displayValue": "Yellow"
        },
        {
          "value": "Pink",
          "displayValue": "Pink"
        },
        {
          "value": "Purple",
          "displayValue": "Purple"
        }
      ]
    }
  ],
  "items": [
    {
      "link": {
        "rel": "variation",
        "href": "https://pm.epages.com/rs/shops/apidocu/products/561B822B-8387-3A70-BE21-D5809AB338DD"
      },
      "attributeSelection": [
        {
          "name": "Colour",
          "value": "Silver"
        }
      ]
    },
    {
      "link": {
        "rel": "variation",
        "href": "https://pm.epages.com/rs/shops/apidocu/products/561B822B-3805-771D-8968-D5809AB338A4"
      },
      "attributeSelection": [
        {
          "name": "Colour",
          "value": "White"
        }
      ]
    },
    {
      "link": {
        "rel": "variation",
        "href": "https://pm.epages.com/rs/shops/apidocu/products/561B822B-40EC-A918-DEBC-D5809AB3385B"
      },
      "attributeSelection": [
        {
          "name": "Colour",
          "value": "Green"
        }
      ]
    }
  ],
  "results": 3,
  "resultsPerPage": 10,
  "page": 1,
  "links": []
}

=== ePages-de/epages-docs/_raml/v-7.5.0/apps/products/examples/get_product_productid_variations_response.json
{
  "variationAttributes": [
    {
      "name": "Colour",
      "displayName": "Colour",
      "values": [
        {
          "value": "DeepBlack",
          "displayValue": "Extreme Black"
        },
        {
          "value": "Silver",
          "displayValue": "Silver"
        },
        {
          "value": "Red",
          "displayValue": "Red"
        },
        {
          "value": "OffWhite",
          "displayValue": "Cream"
        },
        {
          "value": "Orange",
          "displayValue": "Orange"
        },
        {
          "value": "Blue",
          "displayValue": "Blue"
        },
        {
          "value": "Green",
          "displayValue": "Green"
        },
        {
          "value": "Yellow",
          "displayValue": "Yellow"
        },
        {
          "value": "Pink",
          "displayValue": "Pink"
        },
        {
          "value": "Purple",
          "displayValue": "Lilac"
        }
      ]
    }
  ],
  "items": [
    {
      "link": {
        "rel": "variation",
        "href": "https://pm.epages.com/rs/shops/apidocu/products/561B822B-8387-3A70-BE21-D5809AB338DD"
      },
      "attributeSelection": [
        {
          "name": "Colour",
          "value": "Silver"
        }
      ]
    },
    {
      "link": {
        "rel": "variation",
        "href": "https://pm.epages.com/rs/shops/apidocu/products/561B822B-3805-771D-8968-D5809AB338A4"
      },
      "attributeSelection": [
        {
          "name": "Colour",
          "value": "White"
        }
      ]
    },
    {
      "link": {
        "rel": "variation",
        "href": "https://pm.epages.com/rs/shops/apidocu/products/561B822B-40EC-A918-DEBC-D5809AB3385B"
      },
      "attributeSelection": [
        {
          "name": "Colour",
          "value": "Green"
        }
      ]
    }
  ],
  "results": 3,
  "resultsPerPage": 10,
  "page": 1,
  "links": []
}
