=== ePages-de/epages-docs/_raml/apps/product/schema/get_product.schema.json
{
  "$schema": "http://json-schema.org/draft-03/schema",
  "title": "Get Product Schema",
  "type": "object",
  "properties": {
    "results": {
      "description": "The number of products in total."
    },
    "page": {
      "description": "The page number on which the products appears."
    },
    "resultsPerPage": {
      "description": "The number of products returned per page."
    },
    "items": {
      "description": "The list of all products."
    }
  }
}

=== ePages-de/epages-docs/_raml/apps/orders/examples/orders_response.json
{
  "results": 3,
  "page": 1,
  "resultsPerPage": 10,
  "items": [
    {
      "orderId": "56025DA7-FB0B-D680-A937-AC153207AB85",
      "orderNumber": "1003",
      "creationDate": "2009-06-29T15:36:11.000Z",
      "billingAddress": null,
      "shippingAddress": null,
      "invoicedDate": null,
      "shippedDate": null,
      "pendingDate": null,
      "archivedDate": null,
      "dispatchedDate": null,
      "viewedDate": null,
      "comment": null,
      "cancelledDate": null,
      "closedDate": null,
      "paidDate": null,
      "returnedDate": null,
      "lineItemContainer": {
        "grandTotal": null,
        "totalBeforeTax": null,
        "totalTax": null,
        "lineItemsSubTotal": null,
        "productLineItems": [],
        "shippingPrice": null
      },
      "links": [
        {
          "rel": "self",
          "href": "http://demo.epages.de:8088/rs/shops/DemoShop/orders/56025DA7-FB0B-D680-A937-AC153207AB85"
        }
      ]
    },
    {
      "orderId": "56025DA7-CC68-0B65-C26E-AC153207ABF5",
      "orderNumber": "1002",
      "creationDate": "2009-06-28T14:58:58.000Z",
      "billingAddress": null,
      "shippingAddress": null,
      "invoicedDate": null,
      "shippedDate": null,
      "pendingDate": null,
      "archivedDate": null,
      "dispatchedDate": null,
      "viewedDate": null,
      "comment": null,
      "cancelledDate": null,
      "closedDate": null,
      "paidDate": null,
      "returnedDate": null,
      "lineItemContainer": {
        "grandTotal": null,
        "totalBeforeTax": null,
        "totalTax": null,
        "lineItemsSubTotal": null,
        "productLineItems": [],
        "shippingPrice": null
      },
      "links": [
        {
          "rel": "self",
          "href": "http://demo.epages.de:8088/rs/shops/DemoShop/orders/56025DA7-CC68-0B65-C26E-AC153207ABF5"
        }
      ]
    },
    {
      "orderId": "56025DA5-CADF-1D4E-5C89-AC153207AB36",
      "orderNumber": "1001",
      "creationDate": "2009-06-21T14:45:11.000Z",
      "billingAddress": null,
      "shippingAddress": null,
      "invoicedDate": null,
      "shippedDate": null,
      "pendingDate": null,
      "archivedDate": null,
      "dispatchedDate": null,
      "viewedDate": null,
      "comment": null,
      "cancelledDate": null,
      "closedDate": null,
      "paidDate": null,
      "returnedDate": null,
      "lineItemContainer": {
        "grandTotal": null,
        "totalBeforeTax": null,
        "totalTax": null,
        "lineItemsSubTotal": null,
        "productLineItems": [],
        "shippingPrice": null
      },
      "links": [
        {
          "rel": "self",
          "href": "http://demo.epages.de:8088/rs/shops/DemoShop/orders/56025DA5-CADF-1D4E-5C89-AC153207AB36"
        }
      ]
    }
  ]
}

=== ePages-de/epages-docs/_raml/v-6.17.50/apps/customers/examples/get_customer_response.json
{
  "results": 3,
  "page": 1,
  "resultsPerPage": 10,
  "items": [
    {
      "customerId": "563874DA-7AE7-9876-9E59-D5809AB38A25",
      "customerNumber": "1027",
      "creationDate": "2015-11-03T08:48:26Z",
      "billingAddress": {
        "company": "Schneiderei",
        "salutation": "Mrs",
        "firstName": "Tanja",
        "lastName": "Schneider",
        "street": "Schneiderstra√üe 10",
        "streetDetails": null,
        "zipCode": "12345",
        "city": "Berlin",
        "state": null,
        "country": "DE",
        "title": null,
        "vatId": null,
        "birthday": null,
        "emailAddress": "schneider@schneiderei.de"
      },
      "internalNote": null,
      "links": [
        {
          "rel": "self",
          "href": "https://pm.epages.com/rs/shops/apidocu/customers/563874DA-7AE7-9876-9E59-D5809AB38A25"
        },
        {
          "rel": "orders",
          "href": "https://pm.epages.com/rs/shops/apidocu/orders?customerId=563874DA-7AE7-9876-9E59-D5809AB38A25"
        }
      ]
    },
    {
      "customerId": "56389403-55BC-176C-5343-D5809AB3A579",
      "customerNumber": "1028",
      "creationDate": "2015-11-03T11:01:23Z",
      "billingAddress": {
        "company": "Boehm-Jacobs",
        "salutation": null,
        "firstName": "Walter",
        "lastName": "Ankunding",
        "street": "Barrows Mountain 8",
        "streetDetails": null,
        "zipCode": "89708-4738",
        "city": "Lunaview",
        "state": null,
        "country": "GB",
        "title": null,
        "vatId": null,
        "birthday": "1975-11-08",
        "emailAddress": "Ankunding@bj.com"
      },
      "internalNote": null,
      "links": [
        {
          "rel": "self",
          "href": "https://pm.epages.com/rs/shops/apidocu/customers/56389403-55BC-176C-5343-D5809AB3A579"
        },
        {
          "rel": "orders",
          "href": "https://pm.epages.com/rs/shops/apidocu/orders?customerId=56389403-55BC-176C-5343-D5809AB3A579"
        }
      ]
    },
    {
      "customerId": "5638A1B2-0580-CA34-5DB3-D5809AB3A51C",
      "customerNumber": "1029",
      "creationDate": "2015-11-03T11:59:46Z",
      "billingAddress": {
        "company": "Ryan and Sons",
        "salutation": "Mr",
        "firstName": "Aaron",
        "lastName": "Grady",
        "street": "Ardith Route 2",
        "streetDetails": null,
        "zipCode": "16772-2059",
        "city": "Buckborough",
        "state": "GA",
        "country": "US",
        "title": "PhD",
        "vatId": null,
        "birthday": null,
        "emailAddress": "aaron@RyanandSons.com"
      },
      "internalNote": null,
      "links": [
        {
          "rel": "self",
          "href": "https://pm.epages.com/rs/shops/apidocu/customers/5638A1B2-0580-CA34-5DB3-D5809AB3A51C"
        },
        {
          "rel": "orders",
          "href": "https://pm.epages.com/rs/shops/apidocu/orders?customerId=5638A1B2-0580-CA34-5DB3-D5809AB3A51C"
        }
      ]
    }
  ]
}

=== ePages-de/epages-docs/_raml/apps/newsletter/examples/get_newsletter_campaign_response.json
{
  "results": 2,
  "page": 1,
  "resultsPerPage": 10,
  "items": [
    {
      "campaignId": "570BACBD-7FB3-E667-835B-AC15320732BE",
      "language": "en",
      "identifier": "NewTrends_EN",
      "name": "New trends at Schneiderei",
      "description": "Learn more about new trends at schneiderei.com",
      "numberOfSubscribers": 0,
      "subject": "New shop trends"
    },
    {
      "campaignId": "570BACBE-9333-CAB0-40BC-AC153207322B",
      "language": "de",
      "identifier": "NewTrends_DE",
      "name": "Neue Trends in der Schneiderei",
      "description": "Lesen Sie Ã¼ber die neuen Trends bei schneiderei.de",
      "numberOfSubscribers": 0,
      "subject": "Neue Shop-Trends"
    }
  ]
}

=== ePages-de/epages-docs/_raml/apps/manufacturers/examples/get_manufacturers_response.json
{
  "results": 2,
  "page": 1,
  "resultsPerPage": 2,
  "items": [
      {
        "zipCode": null,
        "country": null,
        "street": null,
        "state": null,
        "emailOrContactFormUrl": null,
        "responsiblePersonAddress": null,
        "city": null,
        "streetDetails": null,
        "company": "Tatonka",
        "manufacturerId": "691B2E5A-A321-9921-8A5E-C0A805021988",
        "phoneNumber": null
    },
    {
        "zipCode": "07749",
        "country": "Germany",
        "street": "Heinrich-Heine-Str. 1",
        "state": null,
        "emailOrContactFormUrl": "test@epages.de",
        "responsiblePersonAddress": {
            "zipCode": "07749",
            "country": "Germany",
            "emailAddress": "test@epages.de",
            "street": "Heinrich-Heine-Str. 99",
            "state": null,
            "city": "Jena",
            "streetDetails": null,
            "company": "DJ Oetzi",
            "phoneNumber": null
        },
        "city": "Jena",
        "streetDetails": null,
        "company": "DJ Bass",
        "manufacturerId": "691C23A6-6908-FB99-5807-C0A80502185B",
        "phoneNumber": null
    }
  ]
}

=== ePages-de/epages-docs/_raml/v-6.17.50/apps/orders/examples/get_order_response.json
{
  "results": 3,
  "page": 1,
  "resultsPerPage": 10,
  "items": [
    {
      "orderId": "5639C509-092F-7704-77D3-D5809AB321D8",
      "orderNumber": "ORD151104/1033",
      "creationDate": "2015-11-04T08:42:49.000Z",
      "billingAddress": {
        "company": "Boehm-Jacobs",
        "salutation": null,
        "firstName": "Walter",
        "lastName": "Ankunding",
        "street": "Barrows Mountain 8",
        "streetDetails": null,
        "zipCode": "W11 1ET",
        "city": "London",
        "state": null,
        "country": "UK",
        "title": null,
        "vatId": null,
        "birthday": "1975-11-08",
        "emailAddress": "Ankunding@bj.com"
      },
      "shippingAddress": null,
      "shippingData": {
        "shippingMethod": {
          "id": "5171DD86-C077-0726-C448-AC14145F9026",
          "name": "Standard delivery"
        },
        "price": {
          "taxType": "GROSS",
          "formatted": "7.00 €",
          "amount": 7,
          "currency": "EUR"
        }
      },
      "paymentData": {
        "paymentMethod": {
          "id": "5171DD86-0714-8E9B-B079-AC14145F900F",
          "name": "Payment in advance"
        },
        "price": {
          "taxType": "GROSS",
          "formatted": "0.00 €",
          "amount": 0,
          "currency": "EUR"
        }
      },
      "invoicedOn": null,
      "partiallyPaidOn": null,
      "deliveredOn": null,
      "partiallyInvoicedOn": null,
      "pendingOn": null,
      "readyForDispatchOn": null,
      "partiallyDispatchedOn": null,
      "archivedOn": null,
      "dispatchedOn": null,
      "viewedOn": "2015-11-04T11:45:07.000Z",
      "customerNumber": "1031",
      "customerId": "56389403-55BC-176C-5343-D5809AB3A579",
      "locale": null,
      "currencyId": "EUR",
      "taxModel": "GROSS",
      "grandTotal": "250.94",
      "totalBeforeTax": "250.94",
      "totalTax": "0",
      "customerComment": null,
      "internalNote": null,
      "rejectedOn": null,
      "inProcessOn": null,
      "closedOn": null,
      "paidOn": "2016-01-20T07:23:47.000Z",
      "returnedOn": null,
      "links": [
        {
          "rel": "self",
          "href": "https://pm.epages.com/rs/shops/apidocu/orders/5639C509-092F-7704-77D3-D5809AB321D8"
        },
        {
          "rel": "customer",
          "href": "https://pm.epages.com/rs/shops/apidocu/customers/56389403-55BC-176C-5343-D5809AB3A579"
        },
        {
          "rel": "shipping-method",
          "href": "https://pm.epages.com/rs/shops/apidocu/shipping-methods/5171DD86-C077-0726-C448-AC14145F9026"
        }
      ]
    },
    {
      "orderId": "5639C473-4265-5299-FDE2-D5809AB36284",
      "orderNumber": "ORD151104/1032",
      "creationDate": "2015-11-04T08:40:17.000Z",
      "customerId": "563874DA-7AE7-9876-9E59-D5809AB38A25",
      "customerNumber": "1027",
      "locale": "de_DE",
      "currencyId": "EUR",
      "taxModel": "GROSS",
      "grandTotal": "9.99",
      "totalBeforeTax": "8.39",
      "totalTax": "1.6",
      "customerComment": "I need the product asap",
      "internalNote": "Tracking code:YAZUN7989",
      "billingAddress": {
        "company": "Schneiderei",
        "salutation": "Mrs",
        "firstName": "Tanja",
        "lastName": "Schneider",
        "street": "Schneiderstraße 10",
        "streetDetails": null,
        "zipCode": "12345",
        "city": "Berlin",
        "state": null,
        "country": "DE",
        "title": null,
        "vatId": null,
        "birthday": null,
        "emailAddress": "schneider@schneiderei.de"
      },
      "shippingAddress": null,
      "shippingData": null,
      "paymentData": {
        "paymentMethod": {
          "id": "5171DD86-0714-8E9B-B079-AC14145F900F",
          "name": "Payment in advance"
        },
        "price": {
          "taxType": "GROSS",
          "formatted": "0.00 €",
          "amount": 0,
          "currency": "EUR"
        }
      },
      "viewedOn": "2015-11-04T08:41:35.000Z",
      "rejectedOn": null,
      "inProcessOn": null,
      "pendingOn": null,
      "readyForDispatchOn": null,
      "partiallyDispatchedOn": null,
      "dispatchedOn": "2015-11-04T08:41:35.000Z",
      "deliveredOn": "2015-11-04T08:41:35.000Z",
      "partiallyInvoicedOn": null,
      "invoicedOn": null,
      "partiallyPaidOn": null,
      "paidOn": "2015-11-04T08:41:35.000Z",
      "returnedOn": null,
      "closedOn": null,
      "archivedOn": null,
      "links": [
        {
          "rel": "self",
          "href": "https://pm.epages.com/rs/shops/apidocu/orders/5639C473-4265-5299-FDE2-D5809AB36284"
        },
        {
          "rel": "customer",
          "href": "https://pm.epages.com/rs/shops/apidocu/customers/563874DA-7AE7-9876-9E59-D5809AB38A25"
        }
      ]
    },
    {
      "orderId": "5638C3E4-03B6-9023-DE5B-D5809AB3777D",
      "orderNumber": "ORD151103/1031",
      "creationDate": "2015-11-03T14:25:40.000Z",
      "customerId": "5638A1B2-0580-CA34-5DB3-D5809AB3A51C",
      "customerNumber": "1029",
      "locale": "de_DE",
      "currencyId": "EUR",
      "taxModel": "GROSS",
      "grandTotal": "196.05",
      "totalBeforeTax": "196.05",
      "totalTax": "0",
      "customerComment": "Please deliver asap.",
      "internalNote": null,
      "billingAddress": {
        "company": "Ryan and Sons",
        "salutation": "Mr",
        "firstName": "Aaron",
        "lastName": "Grady",
        "street": "Ardith Route 2",
        "streetDetails": null,
        "zipCode": "16772-2059",
        "city": "Buckborough",
        "state": "GA",
        "country": "US",
        "title": "PhD",
        "vatId": null,
        "birthday": null,
        "emailAddress": "aaron@RyanandSons.com"
      },
      "shippingAddress": null,
      "shippingData": {
        "shippingMethod": {
          "id": "5171DD86-C077-0726-C448-AC14145F9026",
          "name": "Standard delivery"
        },
        "price": {
          "taxType": "GROSS",
          "formatted": "7.32 €",
          "amount": 7.32,
          "currency": "EUR"
        }
      },
      "paymentData": {
        "paymentMethod": {
          "id": "5171DD86-0714-8E9B-B079-AC14145F900F",
          "name": "Payment in advance"
        },
        "price": {
          "taxType": "GROSS",
          "formatted": "0.00 €",
          "amount": 0,
          "currency": "EUR"
        }
      },
      "viewedOn": "2015-11-03T14:48:50.000Z",
      "rejectedOn": null,
      "inProcessOn": null,
      "pendingOn": null,
      "readyForDispatchOn": null,
      "partiallyDispatchedOn": null,
      "dispatchedOn": null,
      "deliveredOn": null,
      "partiallyInvoicedOn": null,
      "invoicedOn": null,
      "partiallyPaidOn": null,
      "paidOn": null,
      "returnedOn": null,
      "closedOn": null,
      "archivedOn": null,
      "links": [
        {
          "rel": "self",
          "href": "https://pm.epages.com/rs/shops/apidocu/orders/5638C3E4-03B6-9023-DE5B-D5809AB3777D"
        },
        {
          "rel": "customer",
          "href": "https://pm.epages.com/rs/shops/apidocu/customers/5638A1B2-0580-CA34-5DB3-D5809AB3A51C"
        },
        {
          "rel": "shipping-method",
          "href": "https://pm.epages.com/rs/shops/apidocu/shipping-methods/5171DD86-C077-0726-C448-AC14145F9026"
        }
      ]
    }
  ]
}

=== ePages-de/epages-docs/_raml/apps/product/examples/get_product_response.json
{
  "results": 3,
  "page": 1,
  "resultsPerPage": 3,
  "items": [
    {
      "productId": "54EF2E41-FCA8-E0E5-9323-0A0C05E66C2E",
      "name": "Customised headphone",
      "shortDescription": null,
      "description": "Customise your headphone in no time!",
      "images": [
        {
          "url": "https://pm.epages.com/WebRoot/Store/Shops/apidocu/54EF/2E41/FCA8/E0E5/9323/0A0C/05E6/6C2E/001-headphone_h.jpg",
          "classifier": "HotDeal"
        },
        {
          "url": "https://pm.epages.com/WebRoot/Store/Shops/apidocu/54EF/2E41/FCA8/E0E5/9323/0A0C/05E6/6C2E/001-headphone_m.jpg",
          "classifier": "Medium"
        },
        {
          "url": "https://pm.epages.com/WebRoot/Store/Shops/apidocu/54EF/2E41/FCA8/E0E5/9323/0A0C/05E6/6C2E/headphone3.jpg",
          "classifier": "Large"
        },
        {
          "url": "https://pm.epages.com/WebRoot/Store/Shops/apidocu/54EF/2E41/FCA8/E0E5/9323/0A0C/05E6/6C2E/001-headphone_s.jpg",
          "classifier": "Small"
        },
        {
          "url": "https://pm.epages.com/WebRoot/Store/Shops/apidocu/54EF/2E41/FCA8/E0E5/9323/0A0C/05E6/6C2E/001-headphone_xs.jpg",
          "classifier": "Thumbnail"
        }
      ],
      "priceInfo": {
        "quantity": {
          "amount": 1,
          "unit": "piece(s)"
        },
        "price": {
          "taxType": "GROSS",
          "formatted": "299.00 €",
          "amount": 299,
          "currency": "EUR"
        },
        "depositPrice": null,
        "ecoParticipationPrice": null,
        "priceWithDeposits": {
          "taxType": "GROSS",
          "formatted": "299.00 €",
          "amount": 299,
          "currency": "EUR"
        },
        "manufacturerPrice": null,
        "basePrice": null
      },
      "forSale": true,
      "specialOffer": false,
      "deliveryWeight": {
        "amount": 350,
        "unit": "g"
      },
      "shippingMethodsRestrictedTo": null,
      "availabilityText": "",
      "availability": null,
      "energyLabelsString": null,
      "energyLabelSourceFile": null,
      "productDataSheet": null,
      "sfUrl": "http://pm.epages.com/epages/apidocu.sf/?ObjectPath=/Shops/apidocu/Products/Cust001",
      "productNumber": "Cust001",
      "manufacturer": "Dr. Boom",
      "upc": null,
      "ean": null,
      "links": [
        {
          "rel": "self",
          "href": "https://pm.epages.com/rs/shops/apidocu/products/54EF2E41-FCA8-E0E5-9323-0A0C05E66C2E"
        },
        {
          "rel": "custom-attributes",
          "href": "https://pm.epages.com/rs/shops/apidocu/products/54EF2E41-FCA8-E0E5-9323-0A0C05E66C2E/custom-attributes"
        },
        {
          "rel": "categories",
          "href": "https://pm.epages.com/rs/shops/apidocu/products/54EF2E41-FCA8-E0E5-9323-0A0C05E66C2E/categories"
        }
      ]
    },
    {
      "productId": "51E7F905-2E4C-78C2-30C2-AC14145FA4E5",
      "name": "Dr.Boom - Red Power",
      "shortDescription": null,
      "description": "<ul>\n\t<li>Surround Sound</li>\n\t<li>Acoustic Noise Cancelling</li>\n\t<li>Correct fit",
      "images": [
        {
          "url": "https://pm.epages.com/WebRoot/Store/Shops/apidocu/51E7/F905/2E4C/78C2/30C2/AC14/145F/A4E5/013-headphone-red_h.jpg",
          "classifier": "HotDeal"
        },
        {
          "url": "https://pm.epages.com/WebRoot/Store/Shops/apidocu/51E7/F905/2E4C/78C2/30C2/AC14/145F/A4E5/013-headphone-red_m.jpg",
          "classifier": "Medium"
        },
        {
          "url": "https://pm.epages.com/WebRoot/Store/Shops/apidocu/51E7/F905/2E4C/78C2/30C2/AC14/145F/A4E5/013-headphone-red.jpg",
          "classifier": "Large"
        },
        {
          "url": "https://pm.epages.com/WebRoot/Store/Shops/apidocu/51E7/F905/2E4C/78C2/30C2/AC14/145F/A4E5/013-headphone-red_s.jpg",
          "classifier": "Small"
        },
        {
          "url": "https://pm.epages.com/WebRoot/Store/Shops/apidocu/51E7/F905/2E4C/78C2/30C2/AC14/145F/A4E5/013-headphone-red_xs.jpg",
          "classifier": "Thumbnail"
        }
      ],
      "priceInfo": {
        "quantity": {
          "amount": 1,
          "unit": "piece(s)"
        },
        "price": {
          "taxType": "GROSS",
          "formatted": "65.00 €",
          "amount": 65,
          "currency": "EUR"
        },
        "depositPrice": null,
        "ecoParticipationPrice": null,
        "priceWithDeposits": {
          "taxType": "GROSS",
          "formatted": "65.00 €",
          "amount": 65,
          "currency": "EUR"
        },
        "manufacturerPrice": null,
        "basePrice": null
      },
      "forSale": true,
      "specialOffer": false,
      "deliveryWeight": {
        "amount": 260,
        "unit": "g"
      },
      "shippingMethodsRestrictedTo": null,
      "availabilityText": "In stock<br />can be shipped within 3-5 days",
      "availability": "OnStock",
      "energyLabelsString": null,
      "energyLabelSourceFile": null,
      "productDataSheet": null,
      "sfUrl": "http://pm.epages.com/epages/apidocu.sf/?ObjectPath=/Shops/apidocu/Products/HP-003",
      "productNumber": "HP-003",
      "manufacturer": "Bass by Dr.Boom",
      "upc": null,
      "ean": null,
      "links": [
        {
          "rel": "self",
          "href": "https://pm.epages.com/rs/shops/apidocu/products/51E7F905-2E4C-78C2-30C2-AC14145FA4E5"
        },
        {
          "rel": "custom-attributes",
          "href": "https://pm.epages.com/rs/shops/apidocu/products/51E7F905-2E4C-78C2-30C2-AC14145FA4E5/custom-attributes"
        },
        {
          "rel": "categories",
          "href": "https://pm.epages.com/rs/shops/apidocu/products/51E7F905-2E4C-78C2-30C2-AC14145FA4E5/categories"
        }
      ]
    },
    {
      "productId": "51E7F913-5447-240E-77AE-AC14145FA477",
      "name": "Dr.Boom - True Voice",
      "shortDescription": null,
      "description": "Professional headphones. Bass pipe emphasises low tones for a clear, realistic sound. Ergonomically shaped.",
      "images": [
        {
          "url": "https://pm.epages.com/WebRoot/Store/Shops/apidocu/51E7/F913/5447/240E/77AE/AC14/145F/A477/headset1_h.jpg",
          "classifier": "HotDeal"
        },
        {
          "url": "https://pm.epages.com/WebRoot/Store/Shops/apidocu/51E7/F913/5447/240E/77AE/AC14/145F/A477/headset1_m.jpg",
          "classifier": "Medium"
        },
        {
          "url": "https://pm.epages.com/WebRoot/Store/Shops/apidocu/51E7/F913/5447/240E/77AE/AC14/145F/A477/headset1.jpg",
          "classifier": "Large"
        },
        {
          "url": "https://pm.epages.com/WebRoot/Store/Shops/apidocu/51E7/F913/5447/240E/77AE/AC14/145F/A477/headset1_s.jpg",
          "classifier": "Small"
        },
        {
          "url": "https://pm.epages.com/WebRoot/Store/Shops/apidocu/51E7/F913/5447/240E/77AE/AC14/145F/A477/headset1_xs.jpg",
          "classifier": "Thumbnail"
        }
      ],
      "priceInfo": {
        "quantity": {
          "amount": 1,
          "unit": "piece(s)"
        },
        "price": {
          "taxType": "GROSS",
          "formatted": "149.99 €",
          "amount": 149.99,
          "currency": "EUR"
        },
        "depositPrice": null,
        "ecoParticipationPrice": null,
        "priceWithDeposits": {
          "taxType": "GROSS",
          "formatted": "149.99 €",
          "amount": 149.99,
          "currency": "EUR"
        },
        "manufacturerPrice": null,
        "basePrice": null
      },
      "forSale": true,
      "specialOffer": false,
      "deliveryWeight": {
        "amount": 310,
        "unit": "g"
      },
      "shippingMethodsRestrictedTo": null,
      "availabilityText": "In stock<br />can be shipped within 3-5 days",
      "availability": "OnStock",
      "energyLabelsString": null,
      "energyLabelSourceFile": null,
      "productDataSheet": null,
      "sfUrl": "http://pm.epages.com/epages/apidocu.sf/?ObjectPath=/Shops/apidocu/Products/HS-001",
      "productNumber": "HS-001",
      "manufacturer": "Bass by Dr.Boom",
      "upc": null,
      "ean": null,
      "links": [
        {
          "rel": "self",
          "href": "https://pm.epages.com/rs/shops/apidocu/products/51E7F913-5447-240E-77AE-AC14145FA477"
        },
        {
          "rel": "custom-attributes",
          "href": "https://pm.epages.com/rs/shops/apidocu/products/51E7F913-5447-240E-77AE-AC14145FA477/custom-attributes"
        },
        {
          "rel": "categories",
          "href": "https://pm.epages.com/rs/shops/apidocu/products/51E7F913-5447-240E-77AE-AC14145FA477/categories"
        }
      ]
    }
  ]
}
