=== ePages-de/epages-docs/_raml/apps/product/schema/get_product_productid.schema.json
{
  "$schema": "http://json-schema.org/draft-03/schema",
  "title": "Get Product ProductId Schema",
  "type": "object",
  "properties": {
    "productId": {
      "description": "The unique identifier of the product."
    },
    "name": {
      "description": "The name of the product."
    },
    "shortDescription": {
      "description": "The short description of the product."
    },
    "description": {
      "description": "The description of the product."
    },
    "images": {
      "description": "The image of the product."
    },
    "priceInfo": {
      "description": "Price information on the product."
    },
    "forSale": {
      "description": "Information on the sale status of the product."
    },
    "specialOffer": {
      "description": "Indicates if the product is a special offer."
    },
    "deliveryWeight": {
      "description": "The delivery weight of the product."
    },
    "shippingMethodsRestrictedTo": {
      "description": "Information on possible shipping method restrictions, e.g. express delivery only."
    },
    "availabilityText": {
      "description": "Additional availablility information for the product."
    },
    "availability": {
      "description": "The availablility of the product, e.g. in stock."
    },
    "energyLabelsString": {
      "description": "Indicates the energy label category and the maximimum limit of the energy label."
    },
    "energyLabelSourceFile": {
      "description": "The source file of the energy label."
    },
    "productDataSheet": {
      "description": "The product data sheet of the product. Has to be available if the product has an energy label."
    },
    "sfUrl": {
      "description": "The link to the product."
    },
    "productNumber": {
      "description": "The product number for the product."
    },
    "manufacturer": {
      "description": "The manufacturer of the product."
    },
    "upc": {
      "description": "The Universal Product Code of the product."
    },
    "ean": {
      "description": "The European Article Number of the product, either EAN-8 or EAN-13."
    },
    "links": {
      "description": "The references the product is linked to."
    }
  }
}

=== ePages-de/epages-docs/_raml/apps/product/examples/get_product_productid_response.json
{
  "productId": "51E7F905-2E4C-78C2-30C2-AC14145FA4E5",
  "name": "Dr.Boom - Red Power",
  "shortDescription": null,
  "description": "<ul>\n\t<li>Surround Sound</li>\n\t<li>Acoustic Noise Cancelling</li>\n\t<li>Correct fit",
  "images": [
    {
      "url": "https://pm.epages.com/WebRoot/Store/Shops/apidocu/51E7/F905/2E4C/78C2/30C2/AC14/145F/A4E5/013-headphone-red_h.jpg",
      "classifier": "HotDeal"
    },
    {
      "url": "https://pm.epages.com/WebRoot/Store/Shops/apidocu/51E7/F905/2E4C/78C2/30C2/AC14/145F/A4E5/013-headphone-red_m.jpg",
      "classifier": "Medium"
    },
    {
      "url": "https://pm.epages.com/WebRoot/Store/Shops/apidocu/51E7/F905/2E4C/78C2/30C2/AC14/145F/A4E5/013-headphone-red.jpg",
      "classifier": "Large"
    },
    {
      "url": "https://pm.epages.com/WebRoot/Store/Shops/apidocu/51E7/F905/2E4C/78C2/30C2/AC14/145F/A4E5/013-headphone-red_s.jpg",
      "classifier": "Small"
    },
    {
      "url": "https://pm.epages.com/WebRoot/Store/Shops/apidocu/51E7/F905/2E4C/78C2/30C2/AC14/145F/A4E5/013-headphone-red_xs.jpg",
      "classifier": "Thumbnail"
    }
  ],
  "priceInfo": {
    "quantity": {
      "amount": 1,
      "unit": "piece(s)"
    },
    "price": {
      "taxType": "GROSS",
      "formatted": "65.00 €",
      "amount": 65,
      "currency": "EUR"
    },
    "depositPrice": null,
    "ecoParticipationPrice": null,
    "priceWithDeposits": {
      "taxType": "GROSS",
      "formatted": "65.00 €",
      "amount": 65,
      "currency": "EUR"
    },
    "manufacturerPrice": null,
    "basePrice": null
  },
  "forSale": true,
  "specialOffer": false,
  "deliveryWeight": {
    "amount": 260,
    "unit": "g"
  },
  "shippingMethodsRestrictedTo": null,
  "availabilityText": "In stock<br />can be shipped within 3-5 days",
  "availability": "OnStock",
  "energyLabelsString": null,
  "energyLabelSourceFile": null,
  "productDataSheet": null,
  "sfUrl": "http://pm.epages.com/epages/apidocu.sf/?ObjectPath=/Shops/apidocu/Products/HP-003",
  "productNumber": "HP-003",
  "manufacturer": "Bass by Dr.Boom",
  "upc": null,
  "ean": null,
  "links": [
    {
      "rel": "self",
      "href": "https://pm.epages.com/rs/shops/apidocu/products/51E7F905-2E4C-78C2-30C2-AC14145FA4E5"
    },
    {
      "rel": "custom-attributes",
      "href": "https://pm.epages.com/rs/shops/apidocu/products/51E7F905-2E4C-78C2-30C2-AC14145FA4E5/custom-attributes"
    },
    {
      "rel": "categories",
      "href": "https://pm.epages.com/rs/shops/apidocu/products/51E7F905-2E4C-78C2-30C2-AC14145FA4E5/categories"
    }
  ]
}
