=== ePages-de/epages-docs/_raml/apps/shipping-method/schema/get_shipping.schema.json
{
  "$schema": "http://json-schema.org/draft-03/schema",
  "title": "Shipping Method Schema",
  "type": "object",
  "properties": {
    "shippingMethodId": {
      "description": "The unique identifier of the shipping method."
    },
    "name": {
      "description": "The name of the shipping method."
    },
    "description": {
      "description": "The description of the shipping method."
    },
    "logo": {
      "description": "The logo of the shipping method as link."
    }
  }
}

=== ePages-de/epages-docs/_raml/apps/shipping-method/examples/get_shipping_response.json
[
  {
    "shippingMethodId": "5171DD86-C077-0726-C448-AC14145F9026",
    "name": "Standard delivery",
    "description": null,
    "logo": null
  },
  {
    "shippingMethodId": "5171DD86-4B9C-4281-30BC-AC14145F908F",
    "name": "Express delivery",
    "description": null,
    "logo": null
  },
  {
    "shippingMethodId": "5171DD86-CCFD-ED56-DBF3-AC14145F900E",
    "name": "Customer pickup",
    "description": null,
    "logo": null
  }
]

=== ePages-de/epages-docs/_raml/apps/shipping-method/examples/shipping_methods.json
[
    {
        "shippingMethodId": "532BBA27-C69F-25CD-1146-AC13320B3780",
        "name": "Standard delivery",
        "description": "Descriptive text of delivery costs and conditions. Can contain HTML",
        "logo": "https://url/to/shippingmethod-logo.png"
    },
    {
        "shippingMethodId": "532BBA27-6AEE-90AE-792F-AC13320B370E",
        "name": "Express delivery",
        "description": "Descriptive text of delivery costs and conditions. Can contain HTML",
        "logo": "https://url/to/shippingmethod-logo.png"
    }
]
