=== ePages-de/epages-docs/_raml/v-7.5.0/apps/tax-classes/schema/get_taxclasses.schema.json
{
  "$schema": "http://json-schema.org/draft-03/schema",
  "title": "Get Tax Classes Schema",
  "type": "object",
  "properties": {
    "results": {
      "type": "integer",
      "description": "The number of tax classes in total."
    },
    "page": {
      "type": "integer",
      "description": "The page number on which the tax classes appears."
    },
    "resultsPerPage": {
      "type": "integer",
      "description": "The number of tax classes returned per page."
    },
    "items": {
      "type": "array of [taxClass](page:apps-data-types#taxclass)",
      "description": "The list of all tax classes."
    },
    "defaultTaxClass": {
      "type": "object of [taxClass](page:apps-data-types#taxclass)",
      "description": "The default tax class."
    },
    "defaultTaxClassDigital": {
      "type": "object of [taxClass](page:apps-data-types#taxclass)",
      "description": "The default tax class for digital products and services."
    }
  }
}

=== ePages-de/epages-docs/_raml/v-7.5.0/apps/tax-classes/examples/get_taxclasses_response.json
{
  "results": 5,
  "page": 1,
  "resultsPerPage": 10,
  "items": [
    {
      "taxClassId": "5446685F-D1DC-0823-D290-D5809AB30FB6",
      "name": "no VAT",
      "links": [
        {
          "rel": "self",
          "href": "https://pm.epages.com/rs/shops/apidocu/tax-classes/5446685F-D1DC-0823-D290-D5809AB30FB6"
        }
      ]
    },
    {
      "taxClassId": "5446685F-A8AF-0E18-9B4F-D5809AB30FBF",
      "name": "standard",
      "links": [
        {
          "rel": "self",
          "href": "https://pm.epages.com/rs/shops/apidocu/tax-classes/5446685F-A8AF-0E18-9B4F-D5809AB30FBF"
        }
      ]
    },
    {
      "taxClassId": "5446685F-8E47-FAB9-87FB-D5809AB30F6D",
      "name": "reduced",
      "links": [
        {
          "rel": "self",
          "href": "https://pm.epages.com/rs/shops/apidocu/tax-classes/5446685F-8E47-FAB9-87FB-D5809AB30F6D"
        }
      ]
    },
    {
      "taxClassId": "54B50D97-A277-9AF2-58A1-D5809AB32230",
      "name": "Digital products and services",
      "links": [
        {
          "rel": "self",
          "href": "https://pm.epages.com/rs/shops/apidocu/tax-classes/54B50D97-A277-9AF2-58A1-D5809AB32230"
        }
      ]
    },
    {
      "taxClassId": "54B50D97-3ADA-E805-55B6-D5809AB3223A",
      "name": "eBooks",
      "links": [
        {
          "rel": "self",
          "href": "https://pm.epages.com/rs/shops/apidocu/tax-classes/54B50D97-3ADA-E805-55B6-D5809AB3223A"
        }
      ]
    }
  ],
  "defaultTaxClass": {
    "taxClassId": "5446685F-A8AF-0E18-9B4F-D5809AB30FBF",
    "name": "standard",
    "links": [
      {
        "rel": "self",
        "href": "https://pm.epages.com/rs/shops/apidocu/tax-classes/5446685F-A8AF-0E18-9B4F-D5809AB30FBF"
      }
    ]
  },
  "defaultTaxClassDigital": {
    "taxClassId": "54B50D97-A277-9AF2-58A1-D5809AB32230",
    "name": "Digital products and services",
    "links": [
      {
        "rel": "self",
        "href": "https://pm.epages.com/rs/shops/apidocu/tax-classes/54B50D97-A277-9AF2-58A1-D5809AB32230"
      }
    ]
  }
}
