=== ePages-de/epages-docs/_raml/apps/legal/schema/get_legal_contact.schema.json
{
  "$schema": "http://json-schema.org/draft-03/schema",
  "title": "Get Legal Contact Information Schema",
  "type": "object",
  "properties": {
    "name": {
      "type": "string",
      "description": "The name that appears on the contact information page, e.g. Contact Us."
    },
    "title": {
      "type": "string",
      "description": "The name of the contact information page, that appears on the browser tab."
    },
    "navigationCaption": {
      "type": "string",
      "description": "The name of the contact information page that appears in the navigation bar."
    },
    "shortDescription": {
      "type": "string",
      "description": "Additional short information that can be given to e.g. better explain what's on the contact information page."
    },
    "description": {
      "type": "string",
      "description": "Additional information that can be added to the contact information page, e.g. tax identification number or bank account."
    },
    "company": {
      "type": "string",
      "description": "The name of the shop."
    },
    "contactPerson": {
      "type": "string",
      "description": "The contact person for the shop, usually the shop owner."
    },
    "contactPersonJobTitle": {
      "type": "string",
      "description": "The job title of the contact person."
    },
    "address": {
      "type": "string",
      "description": "The postal address of the shop."
    },
    "phone": {
      "type": "string",
      "description": "The phone number of the shop."
    },
    "email": {
      "type": "string",
      "description": "The email address of the shop."
    }
  }
}

=== ePages-de/epages-docs/_raml/apps/legal/examples/get_legal_cookie_response.json
{
  "name": "Cookie policy",
  "title": "Cookie policy",
  "navigationCaption": "Cookie policy",
  "description": "Provide your customers with information about the cookie policy and make them aware of the GDPR compliant cookie usage in your shop, e.g. “In the following you can change your cookie settings.“"
}

=== ePages-de/epages-docs/_raml/apps/legal/examples/get_legal_contact_response.json
{
  "name": "Contact information",
  "title": "Contact information",
  "navigationCaption": "Contact information",
  "shortDescription": "<p>technic365</p>\r\n\r\n<p>Linen Hall<br />\r\n162- 168 Regent Street<br />\r\nLondon, W1B 5TF<br />\r\nGroßbritannien</p>",
  "description": "<p>Copyright 2009</p>",
  "company": "technic365",
  "contactPerson": "technic365 epages",
  "contactPersonJobTitle": "Webmaster",
  "address": "<p>Linen Hall<br />\r\n162- 168 Regent Street<br />\r\nLondon, W1B 5TF<br />\r\nGroßbritannien</p>",
  "phone": "+44-207 292 1790",
  "email": "epages.technic365@gmail.com"
}

=== ePages-de/epages-docs/_raml/apps/legal/examples/shippingInformation.json
{
  "name": "Shipping terms",
  "title": "Shipping terms - Timo",
  "navigationCaption": "Delivery",
  "shortDescription": "Possible shipping types and the costs incurred",
  "description": "<p>On this page, provide your customers with detailed information about possible shipping types and the costs incurred. Also display the costs for shipment abroad.<p/><p>Specify which countries you ship to.</p>"
}
